DROP TABLE IF EXISTS users_roles;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS roles;

CREATE TABLE IF NOT EXISTS users (id INTEGER AUTO_INCREMENT, email VARCHAR(50) NOT NULL UNIQUE , username VARCHAR(20) NOT NULL UNIQUE , firstname VARCHAR(20) NOT NULL , lastname VARCHAR(40) NOT NULL , birthday DATETIME NOT NULL , exp LONG NOT NULL , level INTEGER NOT NULL , registered_at DATETIME DEFAULT CURRENT_TIMESTAMP, gender VARCHAR(1) NOT NULL , password VARCHAR(250) NOT NULL , primary key (id));
CREATE TABLE IF NOT EXISTS roles (id INTEGER AUTO_INCREMENT, name VARCHAR(20) NOT NULL , PRIMARY KEY(id));
CREATE TABLE IF NOT EXISTS users_roles (id_users INTEGER, id_roles INTEGER, CONSTRAINT fk_user FOREIGN KEY (id_users) REFERENCES users(id), CONSTRAINT fk_roles FOREIGN KEY (id_roles) REFERENCES roles (id));